### ISSUE TITLE
YUM return empty csv file

### ISSUE THREAD

**Issue by wuliwei9278** [mi94/wsj-stock-downloader#2]
I feel your code has some issues. I tried to download YUM for example, but it does not return anything. Although, when I check the wsj myself, I can get the csv file, what is the reason?

**Comment by mi94** [comment]
I just tried this and was surprised that it still works as I have done a terrible job maintaining this repo. As in, it definitely downloaded data for YUM.

What I did:
In the `tickers` directory I added a file called `yum.txt` and just included `YUM` in the file. I then ran `python multiprocess_getter.py` in the parent directory. The raw data from WSJ was saved to `data/yum/YUM.csv`.

Are you getting any errors in your stack trace?

**Comment by wuliwei9278** [comment]
I also find that using a few ticks seems to be okay. What I did is to put all 500 stocks in sp500 into the tick folder and then running your codes. This would cause some stocks to fail. It is indeterministic so different stocks got missing.

**Comment by mi94** [comment]
I see. I've had success downloading 27k+ tickers in the past, so not sure what the issue is on your end. Maybe the number of pool processes is causing you to hit some WSJ server limit? I have two suggestions:
1) Alter the `retrieve` function to retry the request if it fails with an HTTP status code that makes sense to retry. I'd probably set a limit here, something like 3 retries.
2) Use a number smaller than 24, or drop the multiprocess part altogether and go serially, in addition to (1).

**Comment by jsk1976** [comment]
look like this script not working now. it appears giving 403 error while trying to download data using script.

any idea why
